# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StatMaGIC
                                 A QGIS plugin
 This plugin aids in labelling data for Classification
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-15
        copyright            : (C) 2022 by Jeremy Graham MTRI
        email                : jeremyg@mtu.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import logging
log_format = "%(asctime)s %(levelname)s: %(message)s"
formatter = logging.Formatter(log_format)

class LogStream:
    def __init__(self):
        self.logs = []
    def write(self, log):
        self.logs.append(log)
        print(log)
    def flush(self):
        # TODO: figure out why flush gets called when something is logged
        pass
    def __str__(self):
        return "".join(self.logs)

stream = LogStream()
stream_handler = logging.StreamHandler(stream=stream)
stream_handler.setFormatter(formatter)
stream_handler.setLevel(logging.DEBUG)
logger = logging.getLogger("statmagic_gui")
logger.setLevel(logging.DEBUG)
logger.addHandler(stream_handler)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StatMaGIC class from file StatMaGIC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .statmagic import StatMaGIC
    return StatMaGIC(iface)
