from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_GIDLaCDockWidgetBase(object):
    def setupUi(self, GIDLaCDockWidgetBase):
        GIDLaCDockWidgetBase.setObjectName("GIDLaCDockWidgetBase")
        GIDLaCDockWidgetBase.resize(424, 642)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(147, 1, 141, 17))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(7, 1, 141, 17))
        self.label_2.setObjectName("label_2")
        self.comboBox_raster = gui.QgsMapLayerComboBox(self.dockWidgetContents)
        self.comboBox_raster.setGeometry(QtCore.QRect(7, 21, 131, 21))
        self.comboBox_raster.setObjectName("comboBox_raster")
        self.comboBox_vector = gui.QgsMapLayerComboBox(self.dockWidgetContents)
        self.comboBox_vector.setGeometry(QtCore.QRect(147, 21, 131, 21))
        self.comboBox_vector.setObjectName("comboBox_vector")
        self.PrintBox = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.PrintBox.setGeometry(QtCore.QRect(10, 578, 231, 41))
        self.PrintBox.setFrame(True)
        self.PrintBox.setObjectName("PrintBox")
        self.UseBandSelectionBox = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.UseBandSelectionBox.setGeometry(QtCore.QRect(283, 19, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UseBandSelectionBox.setFont(font)
        self.UseBandSelectionBox.setObjectName("UseBandSelectionBox")
        self.ClusterWholeExtentBox = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.ClusterWholeExtentBox.setGeometry(QtCore.QRect(285, 0, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ClusterWholeExtentBox.setFont(font)
        self.ClusterWholeExtentBox.setObjectName("ClusterWholeExtentBox")
        self.PlotData = QtWidgets.QPushButton(self.dockWidgetContents)
        self.PlotData.setGeometry(QtCore.QRect(246, 582, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PlotData.setFont(font)
        self.PlotData.setObjectName("PlotData")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 391, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.label_tab = QtWidgets.QWidget()
        self.label_tab.setObjectName("label_tab")
        self.MakeTempLayer = QtWidgets.QPushButton(self.label_tab)
        self.MakeTempLayer.setGeometry(QtCore.QRect(262, 10, 121, 25))
        self.MakeTempLayer.setObjectName("MakeTempLayer")
        self.exportTrainingButton = QtWidgets.QPushButton(self.label_tab)
        self.exportTrainingButton.setGeometry(QtCore.QRect(150, 442, 151, 21))
        self.exportTrainingButton.setObjectName("exportTrainingButton")
        self.get_ststs_button = QtWidgets.QPushButton(self.label_tab)
        self.get_ststs_button.setGeometry(QtCore.QRect(5, 10, 121, 25))
        self.get_ststs_button.setObjectName("get_ststs_button")
        self.ButRun_ZS = QtWidgets.QPushButton(self.label_tab)
        self.ButRun_ZS.setGeometry(QtCore.QRect(133, 10, 121, 25))
        self.ButRun_ZS.setObjectName("ButRun_ZS")
        self.stats_table = QtWidgets.QTableWidget(self.label_tab)
        self.stats_table.setGeometry(QtCore.QRect(10, 40, 281, 321))
        self.stats_table.setFrameShape(QtWidgets.QFrame.Box)
        self.stats_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stats_table.setObjectName("stats_table")
        self.stats_table.setColumnCount(0)
        self.stats_table.setRowCount(0)
        self.ApplyStdevMatch = QtWidgets.QPushButton(self.label_tab)
        self.ApplyStdevMatch.setGeometry(QtCore.QRect(10, 372, 161, 21))
        self.ApplyStdevMatch.setObjectName("ApplyStdevMatch")
        self.label_8 = QtWidgets.QLabel(self.label_tab)
        self.label_8.setGeometry(QtCore.QRect(230, 392, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.StdevInputBox1 = QtWidgets.QDoubleSpinBox(self.label_tab)
        self.StdevInputBox1.setGeometry(QtCore.QRect(180, 364, 51, 26))
        self.StdevInputBox1.setMinimum(0.25)
        self.StdevInputBox1.setMaximum(10.0)
        self.StdevInputBox1.setSingleStep(0.25)
        self.StdevInputBox1.setProperty("value", 2.0)
        self.StdevInputBox1.setObjectName("StdevInputBox1")
        self.MinBandMatch = QtWidgets.QSpinBox(self.label_tab)
        self.MinBandMatch.setGeometry(QtCore.QRect(240, 364, 48, 26))
        self.MinBandMatch.setObjectName("MinBandMatch")
        self.refresh_col1_button = QtWidgets.QPushButton(self.label_tab)
        self.refresh_col1_button.setGeometry(QtCore.QRect(294, 50, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.refresh_col1_button.setFont(font)
        self.refresh_col1_button.setObjectName("refresh_col1_button")
        self.refreshTableButton = QtWidgets.QPushButton(self.label_tab)
        self.refreshTableButton.setGeometry(QtCore.QRect(295, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.refreshTableButton.setFont(font)
        self.refreshTableButton.setObjectName("refreshTableButton")
        self.evaluatePolygons = QtWidgets.QPushButton(self.label_tab)
        self.evaluatePolygons.setGeometry(QtCore.QRect(10, 402, 131, 25))
        self.evaluatePolygons.setObjectName("evaluatePolygons")
        self.MinMaxMatch_button = QtWidgets.QPushButton(self.label_tab)
        self.MinMaxMatch_button.setGeometry(QtCore.QRect(10, 432, 111, 21))
        self.MinMaxMatch_button.setObjectName("MinMaxMatch_button")
        self.tabWidget.addTab(self.label_tab, "")
        self.unsupervised_tab = QtWidgets.QWidget()
        self.unsupervised_tab.setObjectName("unsupervised_tab")
        self.MapClusters1 = QtWidgets.QPushButton(self.unsupervised_tab)
        self.MapClusters1.setGeometry(QtCore.QRect(80, 40, 121, 41))
        self.MapClusters1.setObjectName("MapClusters1")
        self.label_4 = QtWidgets.QLabel(self.unsupervised_tab)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 71, 17))
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.NumClusterBox = QtWidgets.QSpinBox(self.unsupervised_tab)
        self.NumClusterBox.setGeometry(QtCore.QRect(20, 40, 48, 26))
        self.NumClusterBox.setMinimum(2)
        self.NumClusterBox.setProperty("value", 5)
        self.NumClusterBox.setObjectName("NumClusterBox")
        self.DetectNumClusters = QtWidgets.QPushButton(self.unsupervised_tab)
        self.DetectNumClusters.setGeometry(QtCore.QRect(20, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetectNumClusters.setFont(font)
        self.DetectNumClusters.setObjectName("DetectNumClusters")
        self.PCAbox = QtWidgets.QCheckBox(self.unsupervised_tab)
        self.PCAbox.setGeometry(QtCore.QRect(90, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PCAbox.setFont(font)
        self.PCAbox.setObjectName("PCAbox")
        self.FuzzinessValue = QtWidgets.QLineEdit(self.unsupervised_tab)
        self.FuzzinessValue.setGeometry(QtCore.QRect(170, 110, 41, 21))
        self.FuzzinessValue.setObjectName("FuzzinessValue")
        self.ArchetypeCheckBox = QtWidgets.QCheckBox(self.unsupervised_tab)
        self.ArchetypeCheckBox.setGeometry(QtCore.QRect(11, 93, 151, 16))
        self.ArchetypeCheckBox.setObjectName("ArchetypeCheckBox")
        self.ConfValue = QtWidgets.QLineEdit(self.unsupervised_tab)
        self.ConfValue.setGeometry(QtCore.QRect(171, 134, 41, 21))
        self.ConfValue.setObjectName("ConfValue")
        self.label_7 = QtWidgets.QLabel(self.unsupervised_tab)
        self.label_7.setGeometry(QtCore.QRect(9, 137, 151, 17))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.unsupervised_tab)
        self.label_6.setGeometry(QtCore.QRect(10, 109, 151, 31))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.unsupervised_tab, "")
        self.supervised_tab = QtWidgets.QWidget()
        self.supervised_tab.setObjectName("supervised_tab")
        self.frame = QtWidgets.QFrame(self.supervised_tab)
        self.frame.setGeometry(QtCore.QRect(10, 213, 171, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.trainRFmodButton = QtWidgets.QPushButton(self.frame)
        self.trainRFmodButton.setGeometry(QtCore.QRect(6, 27, 151, 31))
        self.trainRFmodButton.setObjectName("trainRFmodButton")
        self.withSelectedcheckBox = QtWidgets.QCheckBox(self.frame)
        self.withSelectedcheckBox.setGeometry(QtCore.QRect(10, 71, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.withSelectedcheckBox.setFont(font)
        self.withSelectedcheckBox.setObjectName("withSelectedcheckBox")
        self.mapPredsButton = QtWidgets.QPushButton(self.frame)
        self.mapPredsButton.setGeometry(QtCore.QRect(10, 109, 91, 41))
        self.mapPredsButton.setObjectName("mapPredsButton")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 3, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.numKfoldsBox = QtWidgets.QSpinBox(self.frame)
        self.numKfoldsBox.setGeometry(QtCore.QRect(110, 130, 48, 26))
        self.numKfoldsBox.setMinimum(1)
        self.numKfoldsBox.setSingleStep(2)
        self.numKfoldsBox.setProperty("value", 1)
        self.numKfoldsBox.setObjectName("numKfoldsBox")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(110, 106, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.frame_2 = QtWidgets.QFrame(self.supervised_tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 4, 371, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.Conf_Checkbox = QtWidgets.QCheckBox(self.frame_2)
        self.Conf_Checkbox.setGeometry(QtCore.QRect(163, 19, 181, 16))
        self.Conf_Checkbox.setObjectName("Conf_Checkbox")
        self.errors_CheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.errors_CheckBox.setGeometry(QtCore.QRect(163, 33, 201, 23))
        self.errors_CheckBox.setObjectName("errors_CheckBox")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 24, 81, 31))
        self.label_3.setObjectName("label_3")
        self.BandImportance_CheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.BandImportance_CheckBox.setGeometry(QtCore.QRect(163, 50, 181, 20))
        self.BandImportance_CheckBox.setObjectName("BandImportance_CheckBox")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.label_9.setObjectName("label_9")
        self.samplingRatespinBox = QtWidgets.QSpinBox(self.frame_2)
        self.samplingRatespinBox.setGeometry(QtCore.QRect(150, 75, 51, 23))
        self.samplingRatespinBox.setMinimum(1)
        self.samplingRatespinBox.setMaximum(100)
        self.samplingRatespinBox.setProperty("value", 50)
        self.samplingRatespinBox.setObjectName("samplingRatespinBox")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 141, 20))
        self.label_14.setObjectName("label_14")
        self.max_pix_poly_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.max_pix_poly_spinBox.setGeometry(QtCore.QRect(150, 100, 48, 26))
        self.max_pix_poly_spinBox.setMinimum(10)
        self.max_pix_poly_spinBox.setMaximum(500)
        self.max_pix_poly_spinBox.setSingleStep(10)
        self.max_pix_poly_spinBox.setProperty("value", 100)
        self.max_pix_poly_spinBox.setObjectName("max_pix_poly_spinBox")
        self.TestHoldPct_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.TestHoldPct_spinBox.setGeometry(QtCore.QRect(95, 26, 48, 26))
        self.TestHoldPct_spinBox.setProperty("value", 20)
        self.TestHoldPct_spinBox.setObjectName("TestHoldPct_spinBox")
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(210, 70, 111, 41))
        self.label_25.setObjectName("label_25")
        self.max_sample_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.max_sample_spinBox.setGeometry(QtCore.QRect(306, 74, 51, 30))
        self.max_sample_spinBox.setMinimum(50)
        self.max_sample_spinBox.setMaximum(10000)
        self.max_sample_spinBox.setProperty("value", 250)
        self.max_sample_spinBox.setObjectName("max_sample_spinBox")
        self.lowestSample_CheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.lowestSample_CheckBox.setGeometry(QtCore.QRect(190, 107, 171, 23))
        self.lowestSample_CheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lowestSample_CheckBox.setObjectName("lowestSample_CheckBox")
        self.frame_3 = QtWidgets.QFrame(self.supervised_tab)
        self.frame_3.setGeometry(QtCore.QRect(209, 213, 171, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.numRFitersBox = QtWidgets.QSpinBox(self.frame_3)
        self.numRFitersBox.setGeometry(QtCore.QRect(112, 72, 48, 26))
        self.numRFitersBox.setMinimum(1)
        self.numRFitersBox.setSingleStep(2)
        self.numRFitersBox.setProperty("value", 1)
        self.numRFitersBox.setObjectName("numRFitersBox")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(7, 3, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.randSelButton = QtWidgets.QPushButton(self.frame_3)
        self.randSelButton.setGeometry(QtCore.QRect(16, 26, 141, 31))
        self.randSelButton.setObjectName("randSelButton")
        self.mapMultiModelMode = QtWidgets.QPushButton(self.frame_3)
        self.mapMultiModelMode.setGeometry(QtCore.QRect(10, 110, 141, 41))
        self.mapMultiModelMode.setObjectName("mapMultiModelMode")
        self.frame_4 = QtWidgets.QFrame(self.supervised_tab)
        self.frame_4.setGeometry(QtCore.QRect(10, 141, 371, 61))
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setMidLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 1, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.confidenceCheckBox = QtWidgets.QCheckBox(self.frame_4)
        self.confidenceCheckBox.setGeometry(QtCore.QRect(170, 20, 131, 31))
        self.confidenceCheckBox.setObjectName("confidenceCheckBox")
        self.classProbsCheckBox = QtWidgets.QCheckBox(self.frame_4)
        self.classProbsCheckBox.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.classProbsCheckBox.setObjectName("classProbsCheckBox")
        self.frame_5 = QtWidgets.QFrame(self.supervised_tab)
        self.frame_5.setGeometry(QtCore.QRect(10, 378, 371, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName("frame_5")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(10, 31, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(7, 54, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(183, 34, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(180, 55, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.n_estimators_spinBox = QtWidgets.QSpinBox(self.frame_5)
        self.n_estimators_spinBox.setGeometry(QtCore.QRect(100, 24, 48, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.n_estimators_spinBox.setFont(font)
        self.n_estimators_spinBox.setMinimum(50)
        self.n_estimators_spinBox.setMaximum(1000)
        self.n_estimators_spinBox.setSingleStep(50)
        self.n_estimators_spinBox.setProperty("value", 100)
        self.n_estimators_spinBox.setObjectName("n_estimators_spinBox")
        self.max_features_comboBox = QtWidgets.QComboBox(self.frame_5)
        self.max_features_comboBox.setGeometry(QtCore.QRect(98, 52, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.max_features_comboBox.setFont(font)
        self.max_features_comboBox.setEditable(True)
        self.max_features_comboBox.setMaxVisibleItems(5)
        self.max_features_comboBox.setObjectName("max_features_comboBox")
        self.max_features_comboBox.addItem("")
        self.max_features_comboBox.addItem("")
        self.max_features_comboBox.addItem("")
        self.max_features_comboBox.addItem("")
        self.max_depth_spinBox = QtWidgets.QSpinBox(self.frame_5)
        self.max_depth_spinBox.setGeometry(QtCore.QRect(280, 31, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.max_depth_spinBox.setFont(font)
        self.max_depth_spinBox.setMinimum(2)
        self.max_depth_spinBox.setMaximum(100)
        self.max_depth_spinBox.setObjectName("max_depth_spinBox")
        self.min_sample_spinBox_2 = QtWidgets.QSpinBox(self.frame_5)
        self.min_sample_spinBox_2.setGeometry(QtCore.QRect(280, 54, 48, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.min_sample_spinBox_2.setFont(font)
        self.min_sample_spinBox_2.setMinimum(2)
        self.min_sample_spinBox_2.setObjectName("min_sample_spinBox_2")
        self.custom_RF_checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.custom_RF_checkBox.setGeometry(QtCore.QRect(10, 2, 181, 23))
        self.custom_RF_checkBox.setObjectName("custom_RF_checkBox")
        self.tabWidget.addTab(self.supervised_tab, "")
        self.experimental_tab = QtWidgets.QWidget()
        self.experimental_tab.setObjectName("experimental_tab")
        self.segment_button = QtWidgets.QPushButton(self.experimental_tab)
        self.segment_button.setGeometry(QtCore.QRect(20, 60, 89, 25))
        self.segment_button.setObjectName("segment_button")
        self.segment_scale = QtWidgets.QDoubleSpinBox(self.experimental_tab)
        self.segment_scale.setGeometry(QtCore.QRect(120, 60, 69, 26))
        self.segment_scale.setMaximum(1000.0)
        self.segment_scale.setProperty("value", 10.0)
        self.segment_scale.setObjectName("segment_scale")
        self.segment_sigma = QtWidgets.QDoubleSpinBox(self.experimental_tab)
        self.segment_sigma.setGeometry(QtCore.QRect(200, 60, 69, 26))
        self.segment_sigma.setProperty("value", 0.8)
        self.segment_sigma.setObjectName("segment_sigma")
        self.segment_minSize = QtWidgets.QDoubleSpinBox(self.experimental_tab)
        self.segment_minSize.setGeometry(QtCore.QRect(280, 60, 69, 26))
        self.segment_minSize.setProperty("value", 10.0)
        self.segment_minSize.setObjectName("segment_minSize")
        self.label_20 = QtWidgets.QLabel(self.experimental_tab)
        self.label_20.setGeometry(QtCore.QRect(130, 40, 67, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.experimental_tab)
        self.label_21.setGeometry(QtCore.QRect(200, 40, 67, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.experimental_tab)
        self.label_22.setGeometry(QtCore.QRect(280, 40, 67, 17))
        self.label_22.setObjectName("label_22")
        self.diffGaus_button = QtWidgets.QPushButton(self.experimental_tab)
        self.diffGaus_button.setGeometry(QtCore.QRect(20, 150, 71, 25))
        self.diffGaus_button.setObjectName("diffGaus_button")
        self.dog_lowSigma = QtWidgets.QDoubleSpinBox(self.experimental_tab)
        self.dog_lowSigma.setGeometry(QtCore.QRect(110, 150, 69, 26))
        self.dog_lowSigma.setMaximum(1000.0)
        self.dog_lowSigma.setProperty("value", 2.0)
        self.dog_lowSigma.setObjectName("dog_lowSigma")
        self.dog_highSigma = QtWidgets.QDoubleSpinBox(self.experimental_tab)
        self.dog_highSigma.setGeometry(QtCore.QRect(190, 150, 69, 26))
        self.dog_highSigma.setMaximum(1000.0)
        self.dog_highSigma.setProperty("value", 10.0)
        self.dog_highSigma.setObjectName("dog_highSigma")
        self.label_23 = QtWidgets.QLabel(self.experimental_tab)
        self.label_23.setGeometry(QtCore.QRect(106, 130, 81, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.experimental_tab)
        self.label_24.setGeometry(QtCore.QRect(190, 130, 81, 20))
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.experimental_tab, "")
        self.summary_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.summary_button.setGeometry(QtCore.QRect(340, 580, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.summary_button.setFont(font)
        self.summary_button.setObjectName("summary_button")
        GIDLaCDockWidgetBase.setWidget(self.dockWidgetContents)
        self.retranslateUi(GIDLaCDockWidgetBase)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(GIDLaCDockWidgetBase)
    def retranslateUi(self, GIDLaCDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        GIDLaCDockWidgetBase.setWindowTitle(_translate("GIDLaCDockWidgetBase", "GIDLaC"))
        self.label.setText(_translate("GIDLaCDockWidgetBase", "Polygon Layer"))
        self.label_2.setText(_translate("GIDLaCDockWidgetBase", "Raster Layer"))
        self.UseBandSelectionBox.setText(_translate("GIDLaCDockWidgetBase", "Use Selected \n"
" Bands Only"))
        self.ClusterWholeExtentBox.setText(_translate("GIDLaCDockWidgetBase", "Whole Raster"))
        self.PlotData.setText(_translate("GIDLaCDockWidgetBase", "Spectral Plot \n"
" With Selected"))
        self.MakeTempLayer.setText(_translate("GIDLaCDockWidgetBase", "Make Train Layer"))
        self.exportTrainingButton.setText(_translate("GIDLaCDockWidgetBase", "Export Training Data"))
        self.get_ststs_button.setText(_translate("GIDLaCDockWidgetBase", "Get Band Stats"))
        self.ButRun_ZS.setText(_translate("GIDLaCDockWidgetBase", "Get Matches"))
        self.ApplyStdevMatch.setText(_translate("GIDLaCDockWidgetBase", "Return Stdev Matches"))
        self.label_8.setText(_translate("GIDLaCDockWidgetBase", "Min # Bands \n"
" to Match"))
        self.refresh_col1_button.setText(_translate("GIDLaCDockWidgetBase", "Refresh Band \n"
" Selection"))
        self.refreshTableButton.setText(_translate("GIDLaCDockWidgetBase", "Refresh Table"))
        self.evaluatePolygons.setText(_translate("GIDLaCDockWidgetBase", "Evaluate Polygons"))
        self.MinMaxMatch_button.setText(_translate("GIDLaCDockWidgetBase", "Min/Max Match"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.label_tab), _translate("GIDLaCDockWidgetBase", "Labels"))
        self.MapClusters1.setText(_translate("GIDLaCDockWidgetBase", "Map Clusters \n"
"  (Kmeans)"))
        self.label_4.setText(_translate("GIDLaCDockWidgetBase", "# Clusters"))
        self.DetectNumClusters.setText(_translate("GIDLaCDockWidgetBase", "Detect # \n"
" Clusters"))
        self.PCAbox.setText(_translate("GIDLaCDockWidgetBase", "Standardize and PCA"))
        self.FuzzinessValue.setText(_translate("GIDLaCDockWidgetBase", "2"))
        self.ArchetypeCheckBox.setText(_translate("GIDLaCDockWidgetBase", "Return Archetypes"))
        self.ConfValue.setText(_translate("GIDLaCDockWidgetBase", "0.95"))
        self.label_7.setText(_translate("GIDLaCDockWidgetBase", "Confidence Threshold"))
        self.label_6.setText(_translate("GIDLaCDockWidgetBase", "Fuzziness metric (1-5)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.unsupervised_tab), _translate("GIDLaCDockWidgetBase", "Unsupervised"))
        self.trainRFmodButton.setText(_translate("GIDLaCDockWidgetBase", "Train/Val RF Model "))
        self.withSelectedcheckBox.setText(_translate("GIDLaCDockWidgetBase", "With Selected \n"
" Polygons Only"))
        self.mapPredsButton.setText(_translate("GIDLaCDockWidgetBase", "Map \n"
" Predictions"))
        self.label_12.setText(_translate("GIDLaCDockWidgetBase", "Reserve Pixels Only"))
        self.label_15.setText(_translate("GIDLaCDockWidgetBase", "# Kfolds"))
        self.Conf_Checkbox.setText(_translate("GIDLaCDockWidgetBase", "Print Confusion Matrix"))
        self.errors_CheckBox.setText(_translate("GIDLaCDockWidgetBase", "Print Classification Report"))
        self.label_3.setText(_translate("GIDLaCDockWidgetBase", "Withhold %"))
        self.BandImportance_CheckBox.setText(_translate("GIDLaCDockWidgetBase", "Print Band Importance"))
        self.label_10.setText(_translate("GIDLaCDockWidgetBase", "Model Validation"))
        self.label_9.setText(_translate("GIDLaCDockWidgetBase", "Sampling Rate"))
        self.label_14.setText(_translate("GIDLaCDockWidgetBase", "Max Pixels/ Polygon"))
        self.label_25.setText(_translate("GIDLaCDockWidgetBase", "Max samples \n"
" per Class  "))
        self.lowestSample_CheckBox.setText(_translate("GIDLaCDockWidgetBase", "Use Smallest Class n"))
        self.label_5.setText(_translate("GIDLaCDockWidgetBase", "Number of random \n"
" polygon iterations"))
        self.label_13.setText(_translate("GIDLaCDockWidgetBase", "Reserve Polgyons"))
        self.randSelButton.setText(_translate("GIDLaCDockWidgetBase", "Train/Val RF Model"))
        self.mapMultiModelMode.setText(_translate("GIDLaCDockWidgetBase", "Map Predictions \n"
" (mode if >1)"))
        self.label_11.setText(_translate("GIDLaCDockWidgetBase", "Optional Map Outputs"))
        self.confidenceCheckBox.setText(_translate("GIDLaCDockWidgetBase", "Confidence"))
        self.classProbsCheckBox.setText(_translate("GIDLaCDockWidgetBase", "Class Probabilities"))
        self.label_16.setText(_translate("GIDLaCDockWidgetBase", "n_estimators"))
        self.label_17.setText(_translate("GIDLaCDockWidgetBase", "max_features"))
        self.label_18.setText(_translate("GIDLaCDockWidgetBase", "max_depth"))
        self.label_19.setText(_translate("GIDLaCDockWidgetBase", "min_samp_split"))
        self.max_features_comboBox.setCurrentText(_translate("GIDLaCDockWidgetBase", "sqrt"))
        self.max_features_comboBox.setItemText(0, _translate("GIDLaCDockWidgetBase", "sqrt"))
        self.max_features_comboBox.setItemText(1, _translate("GIDLaCDockWidgetBase", "auto"))
        self.max_features_comboBox.setItemText(2, _translate("GIDLaCDockWidgetBase", "log2"))
        self.max_features_comboBox.setItemText(3, _translate("GIDLaCDockWidgetBase", "None"))
        self.custom_RF_checkBox.setText(_translate("GIDLaCDockWidgetBase", "Use Custom Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.supervised_tab), _translate("GIDLaCDockWidgetBase", "Supervised"))
        self.segment_button.setText(_translate("GIDLaCDockWidgetBase", "Segment"))
        self.label_20.setText(_translate("GIDLaCDockWidgetBase", "Scale"))
        self.label_21.setText(_translate("GIDLaCDockWidgetBase", "Sigma"))
        self.label_22.setText(_translate("GIDLaCDockWidgetBase", "Min Size"))
        self.diffGaus_button.setText(_translate("GIDLaCDockWidgetBase", "DoG"))
        self.label_23.setText(_translate("GIDLaCDockWidgetBase", "Low Sigma"))
        self.label_24.setText(_translate("GIDLaCDockWidgetBase", "High Sigma"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.experimental_tab), _translate("GIDLaCDockWidgetBase", "dev_test"))
        self.summary_button.setText(_translate("GIDLaCDockWidgetBase", "Print \n"
" Summary"))
from qgis import gui
